services:
    db:
        image: postgres:18-alpine
        container_name: gophkeeper_db
        shm_size: 256mb
        # command:
        #     [
        #         "postgres",
        #         "-c",
        #         "log_statement=all",
        #         "-c",
        #         "log_connections=true",
        #         "-c",
        #         "log_disconnections=true",
        #     ]
        env_file: .env
        ports:
            - "5432:5432"
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 10s
            timeout: 5s
            retries: 5

    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gophkeeper_server
        env_file: .env
        environment:
            - DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - JWT_SECRET=${JWT_SECRET}
            - SALT_SECRET=${SALT_SECRET}
        ports:
            - "8082:8082"
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
