// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/keeper.proto

package keeper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoHandler_Echo_FullMethodName = "/com.github.cmrda.gophkeeper.EchoHandler/Echo"
)

// EchoHandlerClient is the client API for EchoHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Echo service definition
type EchoHandlerClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoHandlerClient(cc grpc.ClientConnInterface) EchoHandlerClient {
	return &echoHandlerClient{cc}
}

func (c *echoHandlerClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, EchoHandler_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoHandlerServer is the server API for EchoHandler service.
// All implementations must embed UnimplementedEchoHandlerServer
// for forward compatibility.
//
// Echo service definition
type EchoHandlerServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedEchoHandlerServer()
}

// UnimplementedEchoHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoHandlerServer struct{}

func (UnimplementedEchoHandlerServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoHandlerServer) mustEmbedUnimplementedEchoHandlerServer() {}
func (UnimplementedEchoHandlerServer) testEmbeddedByValue()                     {}

// UnsafeEchoHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoHandlerServer will
// result in compilation errors.
type UnsafeEchoHandlerServer interface {
	mustEmbedUnimplementedEchoHandlerServer()
}

func RegisterEchoHandlerServer(s grpc.ServiceRegistrar, srv EchoHandlerServer) {
	// If the following call pancis, it indicates UnimplementedEchoHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoHandler_ServiceDesc, srv)
}

func _EchoHandler_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoHandlerServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoHandler_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoHandlerServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoHandler_ServiceDesc is the grpc.ServiceDesc for EchoHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.cmrda.gophkeeper.EchoHandler",
	HandlerType: (*EchoHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoHandler_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keeper.proto",
}
