// Code generated by MockGen. DO NOT EDIT.
// Source: server/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=server/repository/repository.go -destination=server/mocks/repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository
